import React from 'react';
import './contenido.css';

function Contenido() {
  return (
    <main class="contenido">
        <h3>Contenido</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem distinctio quos fugiat aperiam nesciunt est, iure quisquam reiciendis nihil amet aliquid laboriosam nobis in ad harum asperiores maxime praesentium sequi minus laudantium sapiente sunt corporis odio suscipit? Harum tempora fugit eaque necessitatibus earum odit asperiores voluptate, iste quaerat. Hic nam sequi neque, officiis nesciunt officia, laboriosam maiores quod libero rerum mollitia dolor maxime itaque animi nulla sunt est cum impedit nobis! Ipsum veritatis obcaecati aliquam molestiae mollitia. Harum nulla cumque optio at necessitatibus velit molestiae in eos corrupti? Libero accusantium sit suscipit a eius quos beatae, quis quibusdam quod error voluptatem nihil rerum! Debitis rem sint quibusdam delectus, sapiente ipsa soluta sit minus facere eius cupiditate veritatis culpa aut. Sed eos ipsam corrupti vel voluptates laborum atque, impedit modi voluptas quam eaque soluta tempora est qui obcaecati? Ipsa optio minima explicabo inventore, quasi eveniet vel maiores fugit nam assumenda tempore aliquid quas ea sit illum ut voluptatem. Impedit ex doloremque ullam incidunt. Quos asperiores totam qui nisi quo numquam repudiandae inventore, dolorum, distinctio impedit consequatur eos ullam reprehenderit ratione dicta ad? Quisquam temporibus doloribus alias illo eveniet, perferendis molestiae dolorum minus nam placeat fuga quam omnis corporis, beatae, labore cupiditate.

Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officia quisquam officiis a alias ducimus illo aut nostrum hic placeat dicta iure rem reiciendis ratione error eaque cupiditate veritatis quam aliquam, dolore consectetur accusamus? At laborum commodi itaque nemo deserunt vero sed quisquam porro? Consequatur error, dolor quos nihil nemo expedita ea temporibus non, repudiandae consectetur blanditiis, dolorum quod? Est in aspernatur totam. Assumenda inventore dolor omnis, odit natus dolorem harum vel in asperiores laboriosam quaerat odio voluptatem quibusdam error quasi eum ullam commodi qui tenetur ut sapiente quos provident ipsam. Quae tenetur explicabo illo expedita odit? Cumque, sed! Quis itaque vero rem assumenda, ab minima reprehenderit sunt omnis, ducimus qui eligendi, inventore ex nisi? Nulla harum explicabo mollitia exercitationem? Incidunt deserunt repellendus, error labore, nihil distinctio, porro accusamus quisquam dolores omnis ut quidem dolore enim quo sequi eius natus rem repudiandae ratione? Inventore rem eos harum ab atque, libero eveniet facilis pariatur illum commodi ad soluta tempore nesciunt eligendi similique ratione consequatur eum, adipisci quasi quisquam! Dolores, quis tempore eum suscipit numquam sit praesentium in ut harum debitis hic voluptas esse recusandae aliquid labore quibusdam voluptatibus quae veritatis corporis minus natus. Voluptates, laboriosam similique perspiciatis nulla velit ratione, quod harum sint excepturi sed unde rem? Minus ducimus ipsa perspiciatis odio facilis illum. Cumque velit quis dolorem similique iusto sint eligendi illo rem ipsum quod ullam, accusamus facilis doloremque veniam impedit praesentium optio a sunt doloribus ut voluptate. Nesciunt possimus ipsam obcaecati aliquid esse, deserunt error eum id minus officia unde quidem voluptatum reprehenderit ipsum? Recusandae consectetur placeat excepturi aut quod, dolor vero consequuntur illum, illo perferendis in a amet pariatur! In quam saepe eos maiores reiciendis architecto nulla laborum laboriosam numquam corrupti quasi voluptas a molestias hic officia, et quia minima nemo exercitationem reprehenderit? Nesciunt perferendis nemo nulla id? Maiores, hic facilis excepturi accusamus beatae voluptates aspernatur dicta eveniet voluptatem? Quos dignissimos laudantium repellat qui, soluta repellendus rerum esse blanditiis molestias hic vero exercitationem placeat sint facilis amet quasi. Doloremque asperiores consequuntur reiciendis aperiam ipsum quam laborum repellendus officia neque architecto dolorem, exercitationem at animi incidunt. Illo minus porro blanditiis molestiae id. Ducimus est recusandae nisi reiciendis, ab obcaecati veniam debitis rerum? Accusamus mollitia dolores voluptates eos impedit aliquid quod, ex, repellendus labore rem eligendi necessitatibus corporis ut at totam minus enim neque sit? Totam, possimus cum suscipit qui repudiandae aut eligendi laborum harum hic in quis libero, perferendis vero!</p>
    </main>
  );
}

export default Contenido;